DROP TABLE IF EXISTS lotto;
DROP TABLE IF EXISTS multi;

CREATE TABLE lotto(
    id INTEGER PRIMARY KEY NOT NULL,
    date VARCHAR(10) NOT NULL,
    l1 VARCHAR(2) NOT NULL,
    l2 VARCHAR(2) NOT NULL,
    l3 VARCHAR(2) NOT NULL,
    l4 VARCHAR(2) NOT NULL,
    l5 VARCHAR(2) NOT NULL,
    l6 VARCHAR(2) NOT NULL,
    p1 VARCHAR(2),
    p2 VARCHAR(2),
    p3 VARCHAR(2),
    p4 VARCHAR(2),
    p5 VARCHAR(2),
    p6 VARCHAR(2)
);

CREATE TABLE multi(
    id INTEGER PRIMARY KEY NOT NULL,
    date VARCHAR(16),
    m1 VARCHAR(2) NOT NULL,
    m2 VARCHAR(2) NOT NULL,
    m3 VARCHAR(2) NOT NULL,
    m4 VARCHAR(2) NOT NULL,
    m5 VARCHAR(2) NOT NULL,
    m6 VARCHAR(2) NOT NULL,
    m7 VARCHAR(2) NOT NULL,
    m8 VARCHAR(2) NOT NULL,
    m9 VARCHAR(2) NOT NULL,
    m10 VARCHAR(2) NOT NULL,
    m11 VARCHAR(2) NOT NULL,
    m12 VARCHAR(2) NOT NULL,
    m13 VARCHAR(2) NOT NULL,
    m14 VARCHAR(2) NOT NULL,
    m15 VARCHAR(2) NOT NULL,
    m16 VARCHAR(2) NOT NULL,
    m17 VARCHAR(2) NOT NULL,
    m18 VARCHAR(2) NOT NULL,
    m19 VARCHAR(2) NOT NULL,
    m20 VARCHAR(2) NOT NULL,
    plus VARCHAR(2) NOT NULL
);

